services:
  db:
    image: "${POSTGRES_IMAGE}"
    container_name: test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - test_db_data:/var/lib/postgresql/data

  springboot:
    build:
      context: ./backend/policourt-backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - FLYWAY_URL=jdbc:postgresql://db:5432/test
      - FLYWAY_USER=test
      - FLYWAY_PASSWORD=test
    depends_on:
      - db

  fastapi:
    build:
      context: ./backend/fastapi
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - fastapi
      - springboot

volumes:
  test_db_data:
